apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dev-fusion-ms-hpa
  namespace: dev
  labels:
    env: dev
    app: fusion-ms-ms
    layer: frontend
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-fusion-ms-deployment
  targetCPUUtilizationPercentage: 80
